# Different models for different steps
step_models:
  first_thought:
    name: "QWen2.5-72B-Instruct"
    max_tokens: 4096
    temperature: 0.5
  reasoning:
    name: "QWen2.5-72B-Instruct"
    max_tokens: 8192
    temperature: 0.7
  evaluation:
    name: "QWen2.5-72B-Instruct"
    max_tokens: 4096
    temperature: 0.3

processing:
  max_reasoning_iterations: 10
  max_workers: 32
  max_tasks: 100000

logging:
  log_file_path: "output/math_bc_init_trajectories.jsonl"
  main_log_file: "logs/main.log"
  graph_log_file: "logs/graph.log"
  search_cache_file: "search_cache.db"

paths:
  data_file: "data_resource/math_bc_init_seed.jsonl"

api_configs:
  "QWen2.5-32B-Instruct":
    api_base: "QWEN25_32B_API_ADDRESS"
    api_key_env: "QWEN25_32B_API_KEY"
  "QWen2.5-72B-Instruct":
    api_base: "QWEN25_72B_API_ADDRESS"
    api_key_env: "QWEN25_72B_API_KEY"
  "DeepSeek-R1-0528":
    api_base: "DEEPSEEK_R1_API_ADDRESS"
    api_key_env: "DEEPSEEK_R1_API_KEY"
  "default":
    api_base: "DEFAULT_API_ADDRESS"
    api_key_env: "DEFAULT_API_KEY"

