step_models:
  first_thought:
    name: "Qwen2.5-72B-Instruct"
    max_tokens: 4096
    temperature: 0.5
  reasoning:
    name: "Qwen2.5-72B-Instruct"
    max_tokens: 8192
    temperature: 0.7
  evaluation:
    name: "Qwen2.5-72B-Instruct"
    max_tokens: 4096
    temperature: 0.3

processing:
  max_reasoning_iterations: 10
  max_workers: 20
  max_tasks: 100000

logging:
  log_file_path: "output/traces.jsonl"
  main_log_file: "logs/main.log"
  graph_log_file: "logs/graph.log"

# data path
paths:
  data_file: "data/aime.jsonl"

# API configurations for different models
# Use name in step_models first.
# If name in step_models does not exist, use default api.
api_configs:
  "default":
    api_base: "" 
    api_key_env: "DEFAULT_API_KEY"
  "Qwen2.5-72B-Instruct":
    api_base: "" 
    api_key_env: "QWEN25_72B_API_KEY"
