### model
model_name_or_path: /mnt/data/models/Qwen2.5-7B-Instruct
trust_remote_code: true
add_special_tokens: <code>,</code>,<thought>,</thought>,<first_thought>,</first_thought>
resize_vocab: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: configs/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]


### dataset
dataset: BC_init
template: qwen
cutoff_len: 4096
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: checkpoints/SCoRe/math/BC_init_qwen7b
logging_steps: 10
save_steps: 2000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 7.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
